# Generated by Django 2.2.1 on 2019-07-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_user_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
