# Generated by Django 2.2.1 on 2019-07-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sem',
            field=models.IntegerField(default=1),
        ),
    ]
